name: Publish to TestPyPI

on:
  push:
    branches: [ dev, develop, development ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: |
        poetry install --all-extras
    - name: Lint with black
      run: |
        poetry run black --check .
    - name: Test with pytest
      run: |
        poetry run pytest

  build-and-publish-test:
    name: Build and publish to TestPyPI
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Configure TestPyPI repository
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
    - name: Install dependencies
      run: |
        poetry install
    - name: Build package
      run: |
        poetry build
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true 